{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "710c951e_c1e453f3",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 6
      },
      "lineNbr": 0,
      "author": {
        "id": 1000276
      },
      "writtenOn": "2024-02-26T18:27:12Z",
      "side": 1,
      "message": "Seems okay, but would still like to get Zev\u0027s feedback.",
      "revId": "ed682b5c415a0b9518168196c696fc0a1ac8d143",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "5165fcfc_b3dcbd30",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 6
      },
      "lineNbr": 0,
      "author": {
        "id": 1000733
      },
      "writtenOn": "2024-02-27T09:09:54Z",
      "side": 1,
      "message": "I\u0027m a bit confused about exactly what\u0027s now being done with the new line...\n\nDuring initialization in `main()` first we deassert it, and then later assert it just before entering the main event loop -- but both times it\u0027s then immediately reset?  (Explicitly at line 2910, and implicitly in the `hpmLine` dtor at line 3484.)  I\u0027m not clear on (a) what the deassert \u0026 reassert are actually needed for (i.e. what operations in between them actually *need* to be in between them, or why they\u0027re placed where they are), and (b) if they\u0027re actually going to reliably do anything other than just momentarily glitch the state of the line if there\u0027s a `.reset()` right after each one.  Am I misunderstanding something here?",
      "revId": "ed682b5c415a0b9518168196c696fc0a1ac8d143",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}